const CONSUMER_SECRET = 'WEPbtyzLcOgQ1DMRJK3O9UFtVof5XYfMOBgAR29K2Mx6THNFgE';
const TOKEN_SECRET = 'A5DURiTKDKDRJiSiZLjYRt84AALTIq7r6XDKjbQr0cwYK';

module.exports.CONSUMER_SECRET = CONSUMER_SECRET;
module.exports.TOKEN_SECRET = TOKEN_SECRET;
