const CONSUMER_SECRET = 'zhyU5SUolhha4EFxOSpnWG2jq0q7L230TEgSnEYMoPva9KXgaX';
const TOKEN_SECRET = '4q0NL04kBh2CPGAXh7T6bSHROiJL6iwBnaO96tpb5wP3i';

module.exports.CONSUMER_SECRET = CONSUMER_SECRET;
module.exports.TOKEN_SECRET = TOKEN_SECRET;
